services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pandemic_rabbitmq
    ports:
      - "5672:5672"   # TCP порт для спілкування з C# кодом
      - "15672:15672" # HTTP порт для  адмін-панелі в браузері